export const fadeUp = { hidden: { opacity: 0, y: 24 }, visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: 'easeOut' } } };
export const fadeIn = { hidden: { opacity: 0 }, visible: { opacity: 1, transition: { duration: 0.4 } } };
export const scaleIn = { hidden: { opacity: 0, scale: 0.92 }, visible: { opacity: 1, scale: 1, transition: { duration: 0.4, ease: 'easeOut' } } };
export const slideInFromLeft = { hidden: { x: -40, opacity: 0 }, visible: { x: 0, opacity: 1, transition: { duration: 0.4, ease: 'easeOut' } } };
export const modalVariant = { hidden: { opacity: 0, scale: 0.92, y: 12 }, visible: { opacity: 1, scale: 1, y: 0, transition: { duration: 0.3, ease: 'easeOut' } }, exit: { opacity: 0, scale: 0.92, y: 12 } };
export const backdropVariant = { hidden: { opacity: 0 }, visible: { opacity: 1 }, exit: { opacity: 0 } };
export const itemVariants = { hidden: { opacity: 0, x: -8 }, visible: { opacity: 1, x: 0 } };
export const buttonTap = { scale: 0.97 };
export const buttonHover = { scale: 1.03, boxShadow: '0 0 20px rgba(56,189,248,0.4)' };
export const staggerContainer = (delay = 0.05) => ({ hidden: { opacity: 1 }, visible: { transition: { staggerChildren: delay, delayChildren: 0.1 } } });
